version: "3.8"

services: # Lista os serviços a serem executados no Docker
  django-server: # Nome do servidor web do django
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000" # Comandos python para serem executados ao subir o servidor
    volumes:
      - .:/code # Diretório onde arquivos ficarão salvos permanente 
    ports:
      - 8000:8000 # Mapeamento da porta local do PC para a porta do container
    depends_on:
      - db-server # Este serviço depende do serviço aqui indicado

  db-server: # Nome do servidor do postgres
    image: postgres # Utiliza imagem do postgres
    environment: # Variáveis de ambiente
      POSTGRES_DB: ${POSTGRES_NAME} # Nome do banco de dados
      POSTGRES_USER: ${POSTGRES_USER} # Usuário do banco de dados
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # Senha do banco de dados

    ports:
      - 5432:5432 # Mapeamento da porta local do PC para a porta do container

    volumes:
      - postgres_data:/var/lib/postgresql/data/ # Volume que salva permanente os dados do postgres

volumes:
  postgres_data: